# Generated by Django 2.1.3 on 2019-01-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
