# Generated by Django 2.1.3 on 2019-01-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(choices=[('EMAIL', 'Email'), ('SPAM', 'Spam'), ('PHYSICAL', 'Physical')], default='EMAIL', max_length=40)),
            ],
        ),
    ]
